Repository hummingbird-me/kitsu-web, pull requests merged in 2020-03, with the labels that each got.

#810 Fix word wrapping of reactions
  app/styles/layout/_feeds.scss
  app/styles/pages/_media-pages.scss
Labels: type:bug

#861 Bump ember-cli-sass to 10.0.1
  ember-cli-build.js
  package.json
  yarn.lock
Labels: dependencies, javascript

#873 Bump ember-flickity to 0.2.0
  package.json
  yarn.lock
Labels: dependencies, javascript

#807 feat: add French translation to Kitsu
  app/controllers/settings/index.js
  app/routes/application.js
  config/ember-intl.js
  config/environment.js
  ember-cli-build.js
  package.json
  tests/unit/models/library-entry-test.js
  tests/unit/models/user-test.js
  translations/fr-fr.yaml
  yarn.lock
Labels: javascript, type:enhancement

#915 build(deps-dev): update Ember to 3.8
  package.json
  tests/helpers/owner.js
  yarn.lock
Labels: dependencies, javascript

#920 build(deps-dev): update Ember to 3.9
  package.json
  yarn.lock
Labels: dependencies, javascript

#930 build(deps-dev): bump @ember-intl/cp-validations from 3.0.1 to 4.0.1
  package.json
  translations/en-us.yaml
  translations/fr-fr.yaml
  translations/id-id.yaml
  yarn.lock
Labels: dependencies, javascript
